// GENERATED by tools/build-boutique-photos.py — do not edit by hand.
// Declares galleryData so boutique.html can reuse the gallery carousel
// code in script.js. Only ever loaded on boutique.html.
const galleryData = {
  "partywear-bridal": [[900,1200], [900,1200], [900,1200], [800,1200], [900,1200], [900,1200], [1200,1200], [1200,1200], [900,1200]],
  "suits-dresses": [[864,1184], [800,1200], [800,1200], [800,1200], [900,1200], [525,1200], [900,1200], [827,1066], [800,1200], [800,1200], [800,1200], [800,1200], [794,1066], [900,1200], [800,1200], [1024,1024], [1200,1200], [1200,1200]],
  "blouses-rail": [[978,1200], [1200,932], [928,1200], [944,1200], [1200,969], [758,1200], [726,1200], [1200,982], [1200,608], [1200,675], [863,887], [1034,894]],
  "jewelry-rail": [],
  "accessories-rail": [],
};
