#!/usr/bin/env python3
"""Convert Neena's boutique photos into the WebP files the carousels use.

    python3 tools/build-boutique-photos.py

Reads  ../Boutique Photos/<set>/**
Writes Real Images/Boutique/photos/<slug>/<slug>-NN.webp
       boutique-data.js  (sizes + counts, same shape as gallery-data.js)

The carousels reuse the gallery machinery in script.js, so boutique-data.js
deliberately declares `galleryData` — boutique.html loads this file and
gallery.html loads gallery-data.js, never both, so there's no clash.

Requires Pillow:  python3 -m pip install pillow
"""
import os
from PIL import Image, ImageOps

HERE = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.dirname(HERE)
SRC = os.path.join(os.path.dirname(SITE), "Boutique Photos")
DST = os.path.join(SITE, "Real Images", "Boutique", "photos")

MAX_EDGE = 1200
QUALITY = 78
EXTS = (".jpg", ".jpeg", ".png", ".heic", ".webp")

# Source folder -> carousel slug. ORDER lists the filenames that should come
# first; anything not named falls in afterwards in filename order.
#
# Party & Bridal mixes glossy model shots with mannequin and showroom shots, so
# the models lead and the stock shots follow — otherwise the two styles
# alternate and the strip looks accidental. Suits is nearly all model shots,
# with three composite/mannequin frames pushed to the end. Blouses is uniformly
# flat-lay, which is how blouses are actually sold, so it needs no reordering.
SETS = [
    ("Party and Bridal Wear", "partywear-bridal", [
        "IMG-20250929-WA0089.jpg", "IMG-20260205-WA0028.jpg", "IMG-20260526-WA0005.jpg",
        "IMG-20260617-WA0000.jpg", "IMG-20260621-WA0079.jpg", "IMG-20260624-WA0000.jpg",
        "IMG-20260207-WA0041.jpg", "IMG-20260207-WA0053.jpg", "IMG-20250510-WA0060.jpg",
    ]),
    ("Suits and Dresses", "suits-dresses", [
        "IMG-20250917-WA0000.jpg", "IMG-20250921-WA0038.jpg", "IMG-20250921-WA0042.jpg",
        "IMG-20250921-WA0048.jpg", "IMG-20250929-WA0089.jpg", "IMG-20251106-WA0000.jpg",
        "IMG-20251120-WA0005.jpg", "IMG-20251120-WA0006.jpg", "IMG-20260319-WA0002.jpg",
        "IMG-20260319-WA0003.jpg", "IMG-20260319-WA0004.jpg", "IMG-20260617-WA0001.jpg",
        "IMG-20260624-WA0002.jpg", "IMG-20260624-WA0003.jpg", "IMG-20260702-WA0006.jpg",
        "IMG-20260805-WA0002.jpg", "IMG-20251029-WA0010.jpg", "IMG-20260617-WA0002.jpg",
    ]),
    ("Blouses", "blouses-rail", []),
    # Not shot yet. The folders don't have to exist — an empty set writes an
    # empty list to boutique-data.js and script.js hides the rail, so the page
    # never shows a headed carousel with nothing in it. Drop photos into
    # ../Boutique Photos/Jewelry (or /Accessories), rerun, and the rail appears.
    ("Jewelry", "jewelry-rail", []),
    ("Accessories", "accessories-rail", []),
]


def main():
    manifest = {}
    total = 0
    for src_dir, slug, order in SETS:
        found = {}
        for root, _dirs, names in os.walk(os.path.join(SRC, src_dir)):
            for n in names:
                if n.lower().endswith(EXTS):
                    found[n] = os.path.join(root, n)

        named = [found[n] for n in order if n in found]
        rest = [found[n] for n in sorted(found) if n not in set(order)]
        files = named + rest

        missing = [n for n in order if n not in found]
        if missing:
            print(f"  ! {slug}: {len(missing)} name(s) in ORDER not found: {missing[:3]}")

        out_dir = os.path.join(DST, slug)
        os.makedirs(out_dir, exist_ok=True)
        for stale in os.listdir(out_dir):
            if stale.endswith(".webp"):
                os.remove(os.path.join(out_dir, stale))

        dims = []
        for i, path in enumerate(files, 1):
            im = ImageOps.exif_transpose(Image.open(path)).convert("RGB")
            w, h = im.size
            scale = MAX_EDGE / max(w, h)
            if scale < 1:
                im = im.resize((round(w * scale), round(h * scale)), Image.LANCZOS)
            im.save(os.path.join(out_dir, f"{slug}-{i:02d}.webp"), "WEBP",
                    quality=QUALITY, method=6)
            dims.append(list(im.size))

        manifest[slug] = dims
        total += len(files)
        note = "" if files else "   (no photos yet — rail stays hidden)"
        print(f"{slug:18} {len(files):>3} photos{note}")

    lines = [
        "// GENERATED by tools/build-boutique-photos.py — do not edit by hand.",
        "// Declares galleryData so boutique.html can reuse the gallery carousel",
        "// code in script.js. Only ever loaded on boutique.html.",
        "const galleryData = {",
    ]
    for _s, slug, _o in SETS:
        pairs = ", ".join(f"[{w},{h}]" for w, h in manifest[slug])
        lines.append(f'  "{slug}": [{pairs}],')
    lines.append("};")
    with open(os.path.join(SITE, "boutique-data.js"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    print(f"\ntotal {total} photos -> wrote boutique-data.js")


if __name__ == "__main__":
    main()
